Web/ForumSystem.Web/Controllers/AnswersController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.Models;
    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.Infrastructure.Extensions;
    using ForumSystem.Web.InputModels.Answers;
    using ForumSystem.Web.ViewModels.Answers;

    using Microsoft.AspNet.Identity;

    public class AnswersController : BaseController
    {
        public AnswersController(IForumSystemData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            var model =
                this.Data.Answers.All()
                    .Where(a => a.Id == id)
                    .ProjectTo<AnswerViewModel>()
                    .FirstOrDefault();

            return this.View(model);
        }

        [ChildActionOnly]
        public ActionResult GetById(int id)
        {
            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            var model = this.Data.Answers.All().Where(a => a.Id == id).ProjectTo<AnswerViewModel>().FirstOrDefault();

            return this.PartialView("_AnswerDetailPartial", model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = this.Data.Posts.GetById(id);
            if (post == null || post.IsDeleted || post.IsLocked)
            {
                return this.HttpNotFound();
            }

            var inputModel = new AnswerInputModel { PostId = post.Id, Post = post.Title };

            return this.PartialView(inputModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AnswerInputModel input)
        {
            if (input != null && this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var answer = new Answer
                                 {
                                     Content = input.Content,
                                     PostId = input.PostId,
                                     AuthorId = userId
                                 };

                this.Data.Answers.Add(answer);
                this.Data.SaveChanges();

                var post = this.Data.Posts.GetById(answer.PostId);
                post.LastActivity = answer.CreatedOn;

                this.Data.Posts.Update(post);
                this.Data.SaveChanges();

                if (post.AuthorId != userId)
                {
                    var newNotification = new Notification
                                              {
                                                  NotificationType = NotificationType.AnswerPost,
                                                  ItemId = answer.Id,
                                                  SenderId = userId,
                                                  ReceiverId = post.AuthorId
                                              };

                    this.Data.Notifications.Add(newNotification);
                    this.Data.SaveChanges();

                    this.UpdateNotificationsCount(post.Author);
                }

                var viewModel = Mapper.Map<AnswerViewModel>(answer);

                return this.PartialView("_AnswerDetailPartial", viewModel);
            }

            return this.JsonError("Content is required");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userId = this.User.Identity.GetUserId();
            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = new AnswerEditModel { Id = answer.Id, Content = answer.Content };

            return this.PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AnswerEditModel model)
        {
            if (this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var answer = this.Data.Answers.GetById(model.Id);

                if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                answer.Content = model.Content;

                this.Data.Answers.Update(answer);
                this.Data.SaveChanges();

                var viewModel = Mapper.Map<AnswerViewModel>(answer);

                return this.PartialView("_AnswerDetailPartial", viewModel);
            }

            return this.JsonError("Content is required");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = this.Data.Answers.GetById(id);
            if (answer == null || answer.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = Mapper.Map<AnswerViewModel>(answer);

            return this.PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var answer = this.Data.Answers.GetById(id);
            if (answer == null || answer.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            this.Data.Answers.Delete(id);
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", "Posts", new { area = string.Empty, id = answer.PostId });
        }
    }
}

Web/ForumSystem.Web/Controllers/CommentsController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.Models;
    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.Infrastructure.Extensions;
    using ForumSystem.Web.InputModels.Comments;
    using ForumSystem.Web.ViewModels.Comments;

    using Microsoft.AspNet.Identity;

    public class CommentsController : BaseController
    {
        public CommentsController(IForumSystemData data)
            : base(data)
        {
        }

        [ChildActionOnly]
        public ActionResult All(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            var comments =
                this.Data.Comments.All()
                    .Where(c => c.AnswerId == id)
                    .OrderBy(c => c.CreatedOn)
                    .ProjectTo<CommentViewModel>()
                    .ToList();

            return this.PartialView(comments);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comment = this.Data.Comments.GetById(id);
            if (comment == null)
            {
                return this.HttpNotFound();
            }

            var model = this.Data.Comments.All().Where(c => c.Id == id).ProjectTo<CommentViewModel>().FirstOrDefault();

            return this.View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = this.Data.Answers.GetById(id);
            if (answer == null || answer.IsDeleted || answer.Post.IsLocked)
            {
                return this.HttpNotFound();
            }

            var inputModel = new CommentInputModel { AnswerId = answer.Id };

            return this.PartialView(inputModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CommentInputModel input)
        {
            if (input != null && this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var comment = new Comment
                                  {
                                      AnswerId = input.AnswerId,
                                      Content = input.Content,
                                      AuthorId = userId
                                  };

                this.Data.Comments.Add(comment);
                this.Data.SaveChanges();

                var postId = this.Data.Answers.GetById(comment.AnswerId).PostId;
                var post = this.Data.Posts.GetById(postId);

                post.LastActivity = comment.CreatedOn;

                this.Data.Posts.Update(post);
                this.Data.SaveChanges();

                var answer = this.Data.Answers.GetById(comment.AnswerId);
                if (answer.AuthorId != userId)
                {
                    var newNotification = new Notification
                                              {
                                                  NotificationType = NotificationType.CommentAnswer,
                                                  ItemId = comment.Id,
                                                  SenderId = userId,
                                                  ReceiverId = answer.AuthorId
                                              };

                    this.Data.Notifications.Add(newNotification);
                    this.Data.SaveChanges();

                    this.UpdateNotificationsCount(answer.Author);
                }

                var viewModel = Mapper.Map<CommentViewModel>(comment);

                return this.PartialView("_CommentDetailPartial", viewModel);
            }

            return this.JsonError("Content is required");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userId = this.User.Identity.GetUserId();
            var comment = this.Data.Comments.GetById(id);
            if (comment == null)
            {
                return this.HttpNotFound();
            }

            if (comment.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = new CommentEditModel { Id = comment.Id, Content = comment.Content };

            return this.PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CommentEditModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var comment = this.Data.Comments.GetById(model.Id);

                if (comment.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                comment.Content = model.Content;

                this.Data.Comments.Update(comment);
                this.Data.SaveChanges();

                var viewModel = Mapper.Map<CommentViewModel>(comment);

                return this.PartialView("_CommentDetailPartial", viewModel);
            }

            return this.JsonError("Content is required");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comment = this.Data.Comments.GetById(id);
            if (comment == null || comment.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (comment.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = Mapper.Map<CommentViewModel>(comment);

            return this.PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var comment = this.Data.Comments.GetById(id);
            if (comment == null || comment.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (comment.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            this.Data.Comments.Delete(id);
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", "Posts", new { area = string.Empty, id = comment.Answer.PostId });
        }
    }
}

Web/ForumSystem.Web/Controllers/SidebarController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.ViewModels.Categories;
    using ForumSystem.Web.ViewModels.Posts;
    using ForumSystem.Web.ViewModels.Sections;

    public class SidebarController : BaseController
    {
        private const int TopCategoriesCountDefaultValue = 10;

        private const int LastPostsCountDefaultValue = 6;

        public SidebarController(IForumSystemData data)
            : base(data)
        {
        }

        [ChildActionOnly]
        //[OutputCache(Duration = 10 * 60)]
        public ActionResult AllSections()
        {
            var sections = this.Data.Sections.All().ProjectTo<SectionViewModel>().ToList();

            return this.PartialView(sections);
        }

        [ChildActionOnly]
        //[OutputCache(Duration = 10 * 60)]
        public ActionResult TopCategories()
        {
            var categories =
                this.Data.Categories.All()
                    .Where(c => c.Posts.Count(p => !p.IsDeleted) > 0)
                    .OrderByDescending(c => c.Posts.Count)
                    .ProjectTo<CategoryConciseViewModel>()
                    .Take(TopCategoriesCountDefaultValue)
                    .ToList();

            return this.PartialView(categories);
        }

        [ChildActionOnly]
        //[OutputCache(Duration = 30)]
        public ActionResult LastPosts()
        {
            var lastPosts =
                this.Data.Posts.All()
                    .OrderByDescending(p => p.CreatedOn)
                    .ProjectTo<PostConciseViewModel>()
                    .Take(LastPostsCountDefaultValue)
                    .ToList();

            return this.PartialView(lastPosts);
        }
    }
}

Web/ForumSystem.Web/Views/Shared/_AdministrationMenuPartial.cshtml
<li id="administration-menu">
    <a href="">
        <i class="fa fa-unlock"></i>
        Administration
        <span class="caret"></span>
    </a>
</li>
<li>
    <ul class="user-menu dropdown-menu dropdown-caret nested-menu" id="administration-menu-items">
        <li class="divider"></li>
        <li>
            <a href="@Url.Action("All", "Sections", new { area = "Administration" })">Sections</a>
        </li>
        <li>
            <a href="@Url.Action("All", "Categories", new { area = "Administration" })">Categories</a>
        </li>
        <li>
            <a href="@Url.Action("All", "Users", new { area = "Administration" })">Users</a>
        </li>
        <li>
            <a href="@Url.Action("All", "Posts", new { area = "Administration" })">Posts</a>
        </li>
        <li>
            <a href="@Url.Action("All", "Answers", new { area = "Administration" })">Answers</a>
        </li>
        <li>
            <a href="@Url.Action("All", "Comments", new { area = "Administration" })">Comments</a>
        </li>
        <li class="divider"></li>
    </ul>
</li>

<script>
    $(function () {
        $('#administration-menu-items').hide();

        $('#administration-menu').click(function () {
            $(this).next().find('#administration-menu-items').slideToggle(300);
            return false;
        });
    });
</script>

Web/ForumSystem.Web/Views/Shared/_AnonymousUserLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar-user">
    <div class="container container-holder">
        <ul class="nav navbar-nav">
            <li>
                <a href="@Url.Action("Login", "Account", new { area = string.Empty })" id="login-item">
                    Login
                </a>
            </li>
            <li>
                <a href="@Url.Action("Register", "Account", new { area = string.Empty })" id="register-item">
                    Register
                </a>
            </li>
        </ul>
    </div>
</div>

@RenderBody()

Web/ForumSystem.Web/Views/Shared/_CategoryPageLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="category-header-wrapper row">
    <div class="col-sm-12 col-xs-12">
        <h1>Category "@Model.Title"</h1>
        <h2 class="header-title">@Model.Description</h2>
    </div>
</div>
<div class="row">
    @Html.Partial("_SidebarPartial")
    <section class="col-md-9 col-sm-12 article-wrapper">
        @RenderBody()
    </section>
</div>

Web/ForumSystem.Web/Views/Shared/_IndexPageLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="index-sidebar">
        @Html.Partial("_SidebarPartial")
    </div>
    <section class="col-md-9 col-sm-12 article-wrapper">
        @RenderBody()
    </section>
</div>

Web/ForumSystem.Web/Views/Shared/_Layout.cshtml
@using System

@using ForumSystem.Web.Infrastructure.Extensions
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Web tư vấn sinh viên Đại học sư phạm kỹ thuật TP.HCM</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome")

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
</head>
<body>
    <div class="lead-wrapper">
        <div class="header-wrapper">
            <div class="navbar navbar-default margin-bottom">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                         href=" @Html.ActionLink("Web tư vấn UTE","Index", "Home", new { area = string.Empty }, new { @class = "navbar-brand" })
                           
                        
                    </div>

                    @if (User.IsLoggedIn())
                    {
                        @Html.Partial("_UserNavbarPartial");
                    }
                    else
                    {
                        @Html.Partial("_LoginPartial")
                    }
                </div>
            </div>
        </div>
        <div class="heading-wrapper">
            <div class="breadcrumb heading-nav">
                <div class="cell-page-title">
                    <div class="container container-holder">
                        <h1 class="page-title">@ViewBag.Title</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container main-container container-holder">
        @RenderBody()
        <div id="show-modal"></div>
        <hr />
        <footer>
            <p>
                &copy; @DateTime.Now.Year - <a>All Rights Reserved, HCMUTE</a>
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/administration-scripts")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>

Web/ForumSystem.Web/Views/Shared/_LogoutPartial.cshtml
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", new { area = string.Empty }, FormMethod.Post, new { id = "logoutForm" }))
    {
        @Html.AntiForgeryToken()
        <a href="javascript:document.getElementById('logoutForm').submit()">
            <span class="glyphicon glyphicon-off"></span>
            Logout
        </a>
    }
}

Web/ForumSystem.Web/Views/Shared/_ModeratorMenuPartial.cshtml
<li id="moderator-menu">
    <a href="">
        <i class="fa fa-pencil"></i>
        Moderator
        <span class="caret"></span>
    </a>
</li>
<li>
    <ul class="user-menu dropdown-menu dropdown-caret nested-menu" id="moderator-menu-items">
        <li class="divider"></li>
        <li>
            <a href="@Url.Action("All", "PostReports", new { area = "Moderator" })">Posts Reports</a>
        </li>
        <li>
            <a href="@Url.Action("All", "AnswerReports", new { area = "Moderator" })">Answers Reports</a>
        </li>
        <li>
            <a href="@Url.Action("All", "CommentReports", new { area = "Moderator" })">Comments Reports</a>
        </li>
        <li class="divider"></li>
    </ul>
</li>

<script>
    $(function () {
        $('#moderator-menu-items').hide();

        $('#moderator-menu').click(function () {
            $(this).next().find('#moderator-menu-items').slideToggle(300);
            return false;
        });
    });
</script>

Web/ForumSystem.Web/Views/Shared/_NotificationsNavbarPartial.cshtml
<li class="cell">
    @Ajax.ActionLink(" ", "GetLastNotifications", "Notifications", new { area = string.Empty }, new AjaxOptions
{
    HttpMethod = "GET",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "notifications-container",
    OnBegin = "ShowSpinner",
    OnComplete = "RemoveSpinner",
    OnSuccess = "UpdateCounters"
}, new
{
    @class = "dropdown-toggle noti-info fa fa-globe",
    data_toggle = "dropdown",
    id = "noti-btn"
})
    <span class="noti-counter" id="notifications-count">0</span>

    <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close dropdown-noti" id="notifications">
        <li class="dropdown-header">
            <span id="notifications-count-inner">0</span>
            New Notifications
        </li>

        <li class="spinner" id="loading-on-click">
            <i class="fa fa-spinner fa-pulse fa-fw margin-bottom"></i>
        </li>

        <ul class="noti-box" id="notifications-container"></ul>

        <li class="spinner" id="loading-on-scroll">
            <i class="fa fa-spinner fa-pulse fa-fw margin-bottom"></i>
        </li>

        <li class="see-all">
            <a href="@Url.Action("All", "Notifications", new { area = string.Empty })">
                See all
                <i class="fa fa-arrow-right"></i>
            </a>
        </li>
    </ul>
</li>

<script>
    $(function () {
        $.connection.hub.start().done(function () {
            console.log("Notifications Connection is ready.");
        });

        var forumSystem = $.connection.forumSystemHub;

        function updateNotificationsCount(notificationsCount) {
            $('#notifications-count').text(notificationsCount);
            $('#notifications-count-inner').text(notificationsCount);
        }

        forumSystem.client.updateNotificationsCount = updateNotificationsCount;

        $('#notifications-count').load('/Notifications/GetNotificationsCount');
        $('#notifications-count-inner').load('/Notifications/GetNotificationsCount');
    });

    function UpdateCounters() {
        $('#notifications-count').load('/Notifications/GetNotificationsCount');
        $('#notifications-count-inner').load('/Notifications/GetNotificationsCount');
    }

    function ShowSpinner() {
        $('#loading-on-click').css("display", "block");
    }

    function RemoveSpinner() {
        $('#loading-on-click').css("display", "none");
    }
</script>

Web/ForumSystem.Web/Views/Shared/_PostPageLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    @Html.Partial("_SidebarPartial")
    <section class="col-md-9 col-sm-12 article-wrapper">
        @RenderBody()
    </section>
</div>

Web/ForumSystem.Web/Views/Shared/_SectionPageLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section-header-wrapper row">
    <div class="col-sm-8 col-xs-12">
        <h1>Section "@(ViewBag.Title)"</h1>
    </div>
</div>
<div class="row">
    @Html.Partial("_SidebarPartial")
    <section class="col-md-9 col-sm-12 article-wrapper">
        @RenderBody()
    </section>
</div>

Web/ForumSystem.Web/Views/Shared/_SidebarPartial.cshtml
<aside class="col-md-3 col-sm-12 forum-sidebar">
    @Html.Action("AllSections", "Sidebar", new { area = string.Empty })
    @Html.Action("TopCategories", "Sidebar", new { araa = string.Empty })
    @Html.Action("LastPosts", "Sidebar", new { area = string.Empty })
</aside>

Web/ForumSystem.Web/Views/Shared/_UserDefaultImagePartial.cshtml
@using ForumSystem.Common.Constants

@model string

<img src="@GlobalConstants.DefaultUserImagePath" />

Web/ForumSystem.Web/Views/Shared/_UserNavbarPartial.cshtml
@using ForumSystem.Web.Infrastructure.Extensions
@using Microsoft.AspNet.Identity

<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-left table-holder">
        <li>
            <a href="@Url.Action("Index", "Home", new { area = string.Empty })">
                Home
            </a>
        </li>
    </ul>
    <ul class="nav navbar-nav mynav navbar-right table-holder">
        @Html.Partial("_NotificationsNavbarPartial")

        <li class="cell">
            <a data-toggle="dropdown" href="#" class="dropdown-toggle nav-user-photo">
                @Html.Action("GetUserImage", "Users", new { area = string.Empty, id = User.Identity.GetUserId() })
                <span class="nav-user-info">
                    <small>Welcome,</small>
                    <span class="cell username">
                        @User.Identity.GetUserName()
                    </span>
                </span>
                <i class="fa fa-caret-down"></i>
            </a>

            <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                <li>
                    <a href="@Url.Action("Index", "Manage", new { area = string.Empty })">
                        <i class="fa fa-cog"></i>
                        Settings
                    </a>
                </li>
                @if (User.IsAdmin())
                {
                    @Html.Partial("_AdministrationMenuPartial")
                }

                @if (User.IsModerator() || User.IsAdmin())
                {
                    @Html.Partial("_ModeratorMenuPartial")
                }
                <li>
                    <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = User.Identity.GetUserId() })">
                        <i class="fa fa-user"></i>
                        Profile
                    </a>
                </li>

                <li class="divider"></li>
                <li>
                    @Html.Partial("_LogoutPartial")
                </li>
            </ul>
        </li>
    </ul>
</div>

Web/ForumSystem.Web/Views/Shared/_UserPageLayout.cshtml
@using Microsoft.AspNet.Identity

@{
    const string UsersPartialViewsFolder = "~/Views/Users/{0}.cshtml";
    var userId = User.Identity.GetUserId();

    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial(string.Format(UsersPartialViewsFolder, "_ProfileHeadNavigationPartial"), userId)

@RenderBody()