Web/ForumSystem.Web/Areas/Moderator/ViewModels/PostReports/PostReportViewModel.cs
namespace ForumSystem.Web.Areas.Moderator.ViewModels.PostReports
{
    using System;

    using AutoMapper;

    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure.Mapping;

    public class PostReportViewModel : IMapFrom<PostReport>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public string AuthorId { get; set; }

        public string Author { get; set; }

        public int PostId { get; set; }

        public string Post { get; set; }

        public DateTime CreatedOn { get; set; }

        public void CreateMappings(IMapperConfiguration configuration)
        {
            configuration.CreateMap<PostReport, PostReportViewModel>()
                .ForMember(p => p.Author, config => config.MapFrom(p => p.Author.UserName));
            configuration.CreateMap<PostReport, PostReportViewModel>()
                .ForMember(p => p.Post, config => config.MapFrom(p => p.Post.Title));
        }
    }
}

Web/ForumSystem.Web/Areas/Moderator/Controllers/PostReportsController.cs
namespace ForumSystem.Web.Areas.Moderator.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Areas.Moderator.Controllers.Base;
    using ForumSystem.Web.Areas.Moderator.ViewModels.PostReports;

    public class PostReportsController : ModeratorController
    {
        public PostReportsController(IForumSystemData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult All()
        {
            var reports =
                this.Data.PostReports.All().OrderBy(r => r.CreatedOn).ProjectTo<PostReportViewModel>().ToList();

            return this.View(reports);
        }

        [HttpGet]
        public ActionResult GetAllById(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = this.Data.Posts.GetById(id);
            if (post == null)
            {
                return this.HttpNotFound();
            }

            var reports =
                this.Data.PostReports.All()
                    .Where(r => r.PostId == id)
                    .OrderBy(r => r.CreatedOn)
                    .ProjectTo<PostReportViewModel>()
                    .ToList();

            return this.PartialView(reports);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var report = this.Data.PostReports.GetById(id);
            if (report == null)
            {
                return this.HttpNotFound();
            }

            var model = Mapper.Map<PostReportViewModel>(report);

            return this.PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var report = this.Data.PostReports.GetById(id);
            if (report == null)
            {
                return this.HttpNotFound();
            }

            this.Data.PostReports.Delete(id);
            this.Data.SaveChanges();

            return this.RedirectToAction("All");
        }
    }
}

Web/ForumSystem.Web/Controllers/PostReportsController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Net;
    using System.Web.Mvc;

    using ForumSystem.Data.Models;
    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.InputModels.PostReports;

    using Microsoft.AspNet.Identity;

    [Authorize]
    public class PostReportsController : BaseController
    {
        public PostReportsController(IForumSystemData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = this.Data.Posts.GetById(id);
            if (post == null || post.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (post.AuthorId == userId)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var inputModel = new PostReportInputModel { PostId = post.Id };

            return this.PartialView(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostReportInputModel input)
        {
            if (input != null && this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var report = new PostReport
                                 {
                                     PostId = input.PostId, 
                                     AuthorId = userId, 
                                     Description = input.Description
                                 };

                this.Data.PostReports.Add(report);
                this.Data.SaveChanges();

                return this.JsonSuccess("Successfully created report.");
            }

            return this.JsonError("Description is required");
        }
    }
}

Web/ForumSystem.Web/Areas/Moderator/Views/PostReports/All.cshtml
@using System.Collections.Generic

@using NonFactors.Mvc.Grid

@using ForumSystem.Web.Areas.Moderator.ViewModels.PostReports

@model IEnumerable<PostReportViewModel>

@{
    ViewBag.Title = "Post Reports";
    Layout = "~/Areas/Moderator/Views/Shared/_ModeratorLayout.cshtml";
}

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id).Titled("Id");
        columns.Add(model => model.Author).Titled("Author")
            .RenderedAs(model => Html.ActionLink(model.Author, "Details", new { area = string.Empty, controller = "Users", id = model.AuthorId }));
        columns.Add(model => model.Post).Titled("Post")
            .RenderedAs(model => Html.ActionLink(model.Post, "Details", new { area = string.Empty, controller = "Posts", Id = model.PostId }));
        columns.Add(model => model.Description).Titled("Description");
        columns.Add(model => model.CreatedOn).Titled("CreatedOn");
        columns.Add(model => model.Id)
            .Encoded(false)
            .Filterable(false)
            .Sortable(false)
            .RenderedAs(model => Html.Action("Delete", "PostReports", new { area = "Moderator", id = model.Id }));
    })
    .Pageable(pager =>
    {
        pager.PagesToDisplay = 3;
        pager.RowsPerPage = 10;
    })
    .MultiFilterable()
    .Filterable()
    .Sortable()
    .Css("table table-responsive table-bordered table-striped")
    .Empty("No data found")
)

<script>
    $(document).ready(function() {
        $('#post-reports-item').addClass('head-nav-selected-item');
    });
</script>

Web/ForumSystem.Web/Areas/Moderator/Views/PostReports/Delete.cshtml
@using ForumSystem.Web.Areas.Moderator.ViewModels.PostReports

@model PostReportViewModel

<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirm-delete-post-report-@Model.Id">
    Delete
</button>

<div class="modal fade" id="confirm-delete-post-report-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="confirm-delete-post-report-label-@Model.Id">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="confirm-delete-post-report-label-@Model.Id">Delete Report</h4>
            </div>
            @using (Html.BeginForm("Delete", "PostReports", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="modal-body">
                    <p>Are you sure you want to delete this report?</p>
                </div>
                <div class="modal-footer">
                    <div class="form-actions no-color">
                        <button type="button" class="btn btn-default btn-sm pull-left" data-dismiss="modal">Cancel</button>
                        <input type="submit" value="Delete Report" class="btn btn-danger btn-sm pull-right" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Web/ForumSystem.Web/Areas/Moderator/Views/PostReports/GetAllById.cshtml
@using System.Collections.Generic

@using NonFactors.Mvc.Grid

@model IEnumerable<ForumSystem.Web.Areas.Moderator.ViewModels.PostReports.PostReportViewModel>

<div class="modal fade" id="post-reports" tabindex="-1" role="dialog" aria-labelledby="post-reports-label">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="post-reports-label">Reports</h4>
            </div>
            <div class="modal-body">
                @(Html
                    .Grid(Model)
                    .Build(columns =>
                    {
                        columns.Add(model => model.Id).Titled("Id");
                        columns.Add(model => model.Author).Titled("Author")
                            .RenderedAs(model => Html.ActionLink(model.Author, "Details", new { area = string.Empty, controller = "Users", id = model.AuthorId }));
                        columns.Add(model => model.Post).Titled("Post")
                            .RenderedAs(model => Html.ActionLink(model.Post, "Details", new { area = string.Empty, controller = "Posts", Id = model.PostId }));
                        columns.Add(model => model.Description).Titled("Description");
                        columns.Add(model => model.CreatedOn).Titled("CreatedOn");
                        columns.Add(model => model.Id)
                            .Encoded(false)
                            .RenderedAs(model => Html.Action("Delete", "PostReports", new { area = "Moderator", id = model.Id }));
                    })
                    .Css("table table-responsive table-bordered table-striped")
                    .Empty("No data found")
                )
            </div>
            <div class="modal-footer">
                <a href="#" type="button" class="btn btn-default btn-sm pull-left" data-dismiss="modal">Cancel</a>
                <a href="@Url.Action("All", "PostReports", new { area = "Moderator" })" class="btn btn-primary btn-sm pull-right">All reports</a>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        $('.mvc-grid').mvcgrid();
    </script>
}