Web/ForumSystem.Web/ViewModels/Comments/CommentConciseViewModel.cs
namespace ForumSystem.Web.ViewModels.Comments
{
    using System;

    using AutoMapper;

    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure.Mapping;

    public class CommentConciseViewModel : IMapFrom<Comment>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public string AuthorId { get; set; }

        public string Author { get; set; }

        public DateTime CreatedOn { get; set; }

        public void CreateMappings(IMapperConfiguration configuration)
        {
            configuration.CreateMap<Comment, CommentConciseViewModel>()
                .ForMember(c => c.Author, config => config.MapFrom(c => c.Author.UserName));
        }
    }
}

Web/ForumSystem.Web/Areas/Administration/Controllers/CommentsController.cs
namespace ForumSystem.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Areas.Administration.Controllers.Base;
    using ForumSystem.Web.Areas.Administration.InputModels.Comments;
    using ForumSystem.Web.Areas.Administration.ViewModels.Comments;

    public class CommentsController : AdministrationController
    {
        public CommentsController(IForumSystemData data)
            : base(data)
        {
        }

        public ActionResult All()
        {
            var comments =
                this.Data.Comments.AllWithDeleted()
                    .OrderByDescending(c => c.CreatedOn)
                    .ProjectTo<CommentViewModel>()
                    .ToList();

            return this.View(comments);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comment = this.Data.Comments.GetById(id);
            if (comment == null)
            {
                return this.HttpNotFound();
            }

            var model = new CommentEditModel
                            {
                                Id = comment.Id, 
                                Content = comment.Content, 
                                IsDeleted = comment.IsDeleted
                            };

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CommentEditModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var comment = this.Data.Comments.GetById(model.Id);

                comment.Content = model.Content;
                comment.IsDeleted = model.IsDeleted;

                this.Data.Comments.Update(comment);
                this.Data.SaveChanges();

                return this.RedirectToAction("All");
            }

            return this.View(model);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comment = this.Data.Comments.GetById(id);
            if (comment == null)
            {
                return this.HttpNotFound();
            }

            var model = Mapper.Map<CommentViewModel>(comment);

            return this.PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var comment = this.Data.Comments.GetById(id);
            if (comment == null)
            {
                return this.HttpNotFound();
            }

            this.Data.Comments.Delete(id);
            this.Data.SaveChanges();

            return this.RedirectToAction("All");
        }
    }
}

Web/ForumSystem.Web/Controllers/AnswersController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.Models;
    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.Infrastructure.Extensions;
    using ForumSystem.Web.InputModels.Answers;
    using ForumSystem.Web.ViewModels.Answers;

    using Microsoft.AspNet.Identity;

    public class AnswersController : BaseController
    {
        public AnswersController(IForumSystemData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            var model =
                this.Data.Answers.All()
                    .Where(a => a.Id == id)
                    .ProjectTo<AnswerViewModel>()
                    .FirstOrDefault();

            return this.View(model);
        }

        [ChildActionOnly]
        public ActionResult GetById(int id)
        {
            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            var model = this.Data.Answers.All().Where(a => a.Id == id).ProjectTo<AnswerViewModel>().FirstOrDefault();

            return this.PartialView("_AnswerDetailPartial", model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = this.Data.Posts.GetById(id);
            if (post == null || post.IsDeleted || post.IsLocked)
            {
                return this.HttpNotFound();
            }

            var inputModel = new AnswerInputModel { PostId = post.Id, Post = post.Title };

            return this.PartialView(inputModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AnswerInputModel input)
        {
            if (input != null && this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var answer = new Answer
                                 {
                                     Content = input.Content,
                                     PostId = input.PostId,
                                     AuthorId = userId
                                 };

                this.Data.Answers.Add(answer);
                this.Data.SaveChanges();

                var post = this.Data.Posts.GetById(answer.PostId);
                post.LastActivity = answer.CreatedOn;

                this.Data.Posts.Update(post);
                this.Data.SaveChanges();

                if (post.AuthorId != userId)
                {
                    var newNotification = new Notification
                                              {
                                                  NotificationType = NotificationType.AnswerPost,
                                                  ItemId = answer.Id,
                                                  SenderId = userId,
                                                  ReceiverId = post.AuthorId
                                              };

                    this.Data.Notifications.Add(newNotification);
                    this.Data.SaveChanges();

                    this.UpdateNotificationsCount(post.Author);
                }

                var viewModel = Mapper.Map<AnswerViewModel>(answer);

                return this.PartialView("_AnswerDetailPartial", viewModel);
            }

            return this.JsonError("Content is required");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userId = this.User.Identity.GetUserId();
            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = new AnswerEditModel { Id = answer.Id, Content = answer.Content };

            return this.PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AnswerEditModel model)
        {
            if (this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var answer = this.Data.Answers.GetById(model.Id);

                if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                answer.Content = model.Content;

                this.Data.Answers.Update(answer);
                this.Data.SaveChanges();

                var viewModel = Mapper.Map<AnswerViewModel>(answer);

                return this.PartialView("_AnswerDetailPartial", viewModel);
            }

            return this.JsonError("Content is required");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = this.Data.Answers.GetById(id);
            if (answer == null || answer.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = Mapper.Map<AnswerViewModel>(answer);

            return this.PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var answer = this.Data.Answers.GetById(id);
            if (answer == null || answer.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            this.Data.Answers.Delete(id);
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", "Posts", new { area = string.Empty, id = answer.PostId });
        }
    }
}

Web/ForumSystem.Web/Controllers/CommentLikesController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using ForumSystem.Data.Models;
    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.InputModels.CommentLikes;

    using Microsoft.AspNet.Identity;

    [Authorize]
    public class CommentLikesController : BaseController
    {
        public CommentLikesController(IForumSystemData data)
            : base(data)
        {
        }

        [ChildActionOnly]
        public ActionResult Like(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comment = this.Data.Comments.GetById(id);
            if (comment == null || comment.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            var isLiked = this.Data.CommentLikes.All().Any(l => l.UserId == userId && l.CommentId == id && !l.IsDeleted);
            var likesCount = this.Data.CommentLikes.All().Count(a => a.CommentId == id);

            var model = new CommentLikeInputModel
                            {
                                CommentId = comment.Id, 
                                CommentAuthorId = comment.AuthorId, 
                                IsLiked = isLiked, 
                                LikesCount = likesCount
                            };

            return this.PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Like(CommentLikeInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                var comment = this.Data.Comments.GetById(input.CommentId);
                if (comment == null || comment.IsDeleted)
                {
                    return this.HttpNotFound();
                }

                var userId = this.User.Identity.GetUserId();
                if (comment.AuthorId == userId)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var isLiked =
                    this.Data.CommentLikes.All()
                        .Any(l => l.UserId == userId && l.CommentId == input.CommentId && !l.IsDeleted);

                if (isLiked)
                {
                    return this.Dislike(input);
                }

                var newLike = new CommentLike { UserId = userId, CommentId = input.CommentId };

                this.Data.CommentLikes.Add(newLike);
                this.Data.SaveChanges();

                var likesCount = this.Data.CommentLikes.All().Count(a => a.CommentId == input.CommentId);

                input.IsLiked = true;
                input.LikesCount = likesCount;

                var newNotification = new Notification
                                          {
                                              NotificationType = NotificationType.LikePost,
                                              ItemId = comment.Id,
                                              SenderId = userId,
                                              ReceiverId = comment.AuthorId
                                          };

                this.Data.Notifications.Add(newNotification);
                this.Data.SaveChanges();

                this.UpdateNotificationsCount(comment.Author);

                return this.PartialView(input);
            }

            return this.JsonError("Comment id is required");
        }

        private ActionResult Dislike(CommentLikeInputModel input)
        {
            var userId = this.User.Identity.GetUserId();
            var like =
                this.Data.CommentLikes.All()
                    .FirstOrDefault(l => l.UserId == userId && l.CommentId == input.CommentId && !l.IsDeleted);
            if (like != null)
            {
                this.Data.CommentLikes.Delete(like.Id);
                this.Data.SaveChanges();
            }

            var likesCount = this.Data.CommentLikes.All().Count(a => a.CommentId == input.CommentId);

            input.IsLiked = false;
            input.LikesCount = likesCount;

            return this.PartialView("Like", input);
        }
    }
}

Web/ForumSystem.Web/Controllers/CommentReportsController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Net;
    using System.Web.Mvc;

    using ForumSystem.Data.Models;
    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.InputModels.CommentReports;

    using Microsoft.AspNet.Identity;

    [Authorize]
    public class CommentReportsController : BaseController
    {
        public CommentReportsController(IForumSystemData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comment = this.Data.Comments.GetById(id);
            if (comment == null || comment.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (comment.AuthorId == userId)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var inputModel = new CommentReportInputModel { CommentId = comment.Id };

            return this.PartialView(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CommentReportInputModel inputModel)
        {
            if (inputModel != null && this.ModelState.IsValid)
            {
                var userid = this.User.Identity.GetUserId();
                var report = new CommentReport
                                 {
                                     AuthorId = userid, 
                                     CommentId = inputModel.CommentId, 
                                     Description = inputModel.Description
                                 };

                this.Data.CommentReports.Add(report);
                this.Data.SaveChanges();

                return this.JsonSuccess("Successfully created report.");
            }

            return this.JsonError("Description is required");
        }
    }
}

Web/ForumSystem.Web/Views/Comments/All.cshtml
@using System.Collections.Generic
@model IEnumerable<ForumSystem.Web.ViewModels.Comments.CommentViewModel>

@foreach (var comment in Model)
{
    @Html.Partial("_CommentDetailPartial", comment)
}

Web/ForumSystem.Web/Views/Comments/Create.cshtml
@model ForumSystem.Web.InputModels.Comments.CommentInputModel

@using (Ajax.BeginForm("Create", "Comments", new { id = Model.AnswerId }, new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.InsertAfter,
    UpdateTargetId = $"comments-{Model.AnswerId}",
    OnFailure = "showCommentRequiredError",
    OnSuccess = "closeCommentForm"
}))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.AnswerId)
    @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-12">
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, string.Empty, new { @class = "text-danger" })
            <div id="answer-field-validation-error-message"></div>
        </div>
    </div>
    <div class="row top-buffer bottom-buffer post-actions-toolbar">
        <div class="col-md-12">
            <input type="submit" value="Comment" class="btn btn-success pull-left left-buffer"/>
            <input type="button" value="Cancel" class="btn btn-primary pull-right right-buffer" onclick="closeCommentForm()"/>
        </div>
    </div>
}

<script>
    function closeCommentForm() {
        $("#answer-action-container-@Model.AnswerId").empty();
    }

    function showCommentRequiredError(data) {
        $('<div class="top-buffer left-buffer field-validation-error">'
                + data.responseJSON.errorMessage
                + '</div>').prependTo('#answer-field-validation-error-message')
            .delay(3000).fadeOut();
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/ForumSystem.Web/Views/Comments/Delete.cshtml
@model ForumSystem.Web.ViewModels.Comments.CommentViewModel

<div class="modal fade" id="delete-comment-confirm-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="delete-comment-confirm-label-@Model.Id">
    <div class="modal-dialog mofal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="delete-comment-confirm-label-@Model.Id">Delete Comment</h4>
            </div>
            <div id="test">
                @using (Html.BeginForm("Delete", "Comments", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="modal-body">
                        <p>Are you sure you want to delete this comment?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default btn-sm pull-left" data-dismiss="modal">Cancel</button>
                        <input type="submit" value="Delete Comment" class="btn btn-danger btn-sm pull-right" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Web/ForumSystem.Web/Views/Comments/Details.cshtml
@model ForumSystem.Web.ViewModels.Comments.CommentViewModel

@{
    ViewBag.Title = Model.Post;
}

@Html.Action("GetById", "Posts", new { area = string.Empty, id = Model.PostId })
@Html.Action("GetById", "Answers", new { area = string.Empty, id = Model.AnswerId })

<div class="text-center bottom-buffer">
    <a href="@Url.Action("Details", "Answers", new { area = string.Empty, id = Model.AnswerId })" class="btn btn-primary btn-sm bottom-buffer">
        View all comments
    </a>
</div>

@Html.Partial("_CommentDetailPartial", Model)

<div class="text-center">
    <a href="@Url.Action("Details", "Answers", new { area = string.Empty, id = Model.AnswerId })" class="btn btn-primary btn-sm bottom-buffer">
        View all comments
    </a>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#comment-@(Model.Id)").find('.replay-item').addClass('highlighted');
        });
    </script>
}

Web/ForumSystem.Web/Views/Comments/_CommentDetailPartial.cshtml
@using ForumSystem.Web.Infrastructure.Extensions
@using Microsoft.AspNet.Identity

@model ForumSystem.Web.ViewModels.Comments.CommentViewModel

<div id="comment-@Model.Id">
    <article class="forum-post post-item comment-item replay-item">
        <div class="head-post table-holder">
            <div class="cell">
                <div class="user-wrap">
                    <span class="user-avatar">
                        @Html.Action("GetUserImage", "Users", new { area = string.Empty, id = Model.AuthorId })
                    </span>
                    <span class="cell">
                        <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.AuthorId })" class="user-name">@Model.Author</a>
                        @Html.Action("Roles", "Users", new { area = string.Empty, id = Model.AuthorId })
                    </span>
                </div>
            </div>
        </div>
        <div class="post-content">
            @Html.Raw(Model.Content)
        </div>
        <div class="meta-info table-holder meta-details">

            @if (User.IsLoggedIn() && User.Identity.GetUserId() != Model.AuthorId && !Model.IsUpdating)
            {
                <div id="comment-like-@Model.Id">
                    @Html.Action("Like", "CommentLikes", new { area = string.Empty, id = Model.Id })
                </div>
            }
            else
            {
                <div class="cell stats-holder">
                    <div class="table-holder">
                        <div class="cell">
                            <span class="item-wrap votes-post">
                                <span class="icon-holder">
                                    <i class="fa fa-thumbs-o-up"></i>
                                </span>
                                <span class="cell" id="answer-likes-count-@Model.Id">@Model.LikesCount</span>
                            </span>
                        </div>
                    </div>
                </div>
            }

            <div class="cell details-holder">
                <div class="table-holder">
                    <div class="cell">
                        <span class="item-wrap">
                            <span class="icon-holder">
                                <i class="fa fa-clock-o"></i>
                            </span>
                            <span class="post-date">
                                @Model.CreatedOn
                            </span>
                        </span>
                        @if (Model.ModifiedOn.HasValue)
                        {
                            <span class="item-wrap category-wrap">
                                <span class="icon-holder">
                                    <i class="fa fa-refresh"></i>
                                </span>
                                <span class="cell">
                                    <span class="date-time">@Model.ModifiedOn</span>
                                </span>
                            </span>
                        }

                        @if (Model.ReportsCount > 0)
                        {
                            <span class="item-wrap category-wrap" title="Reports">
                                <span class="icon-holder">
                                    <i class="fa fa-exclamation-circle"></i>
                                </span>
                                <span>@Model.ReportsCount</span>
                            </span>
                        }
                    </div>
                </div>
            </div>
        </div>

        @Html.Action("GetById", "CommentUpdates", new { area = string.Empty, id = Model.Id })

        @if (User.IsLoggedIn())
        {
            <div class="meta-info table-holder meta-details post-actions-toolbar">
                <div class="cell buttons-holder">
                    <div class="table-holder">
                        <div class="cell">

                            @if (!Model.IsPostLocked)
                            {
                                @Ajax.ActionLink("Comment", "Create", "Comments", new { area = string.Empty, id = Model.AnswerId }, new AjaxOptions
                                                   {
                                                       HttpMethod = "GET",
                                                       InsertionMode = InsertionMode.Replace,
                                                       UpdateTargetId = $"answer-action-container-{Model.AnswerId}"
                                                   }, new { @class = "btn primary-btn" })
                            }

                            @if (User.Identity.GetUserId() == Model.AuthorId && (!User.IsModerator() && !User.IsAdmin()))
                            {
                                @Ajax.ActionLink("Edit", "Edit", "Comments", new { area = string.Empty, id = Model.Id }, new AjaxOptions
                                                   {
                                                       HttpMethod = "GET",
                                                       InsertionMode = InsertionMode.Replace,
                                                       UpdateTargetId = $"comment-action-container-{@Model.Id}"
                                                   }, new { @class = "btn primary-btn" })
                            }

                            @if (User.IsModerator() || User.IsAdmin())
                            {
                                @Ajax.ActionLink("Edit", "Edit", "Comments", new { area = "Moderator", id = Model.Id }, new AjaxOptions
                                                   {
                                                       HttpMethod = "GET",
                                                       InsertionMode = InsertionMode.Replace,
                                                       UpdateTargetId = $"comment-action-container-{@Model.Id}"
                                                   }, new { @class = "btn primary-btn" })
                            }

                            @if (User.Identity.GetUserId() == Model.AuthorId || User.IsModerator() || User.IsAdmin())
                            {
                                @Ajax.ActionLink("Delete", "Delete", "Comments", new { area = string.Empty, id = Model.Id }, new AjaxOptions
                                                   {
                                                       HttpMethod = "GET",
                                                       InsertionMode = InsertionMode.Replace,
                                                       UpdateTargetId = "show-modal",
                                                       OnSuccess = $"DeleteCommentConfirm_{Model.Id}"
                                                   }, new { @class = "btn primary-btn" })
                            }

                            @if (Model.ReportsCount > 0 && (User.IsModerator() || User.IsAdmin()))
                            {
                                @Ajax.ActionLink("Reports", "GetAllById", "CommentReports", new { area = "Moderator", id = Model.Id }, new AjaxOptions
                                                   {
                                                       HttpMethod = "GET",
                                                       InsertionMode = InsertionMode.Replace,
                                                       UpdateTargetId = "show-modal",
                                                       OnSuccess = $"LoadCommentReports_{Model.Id}"
                                                   }, new { @class = "btn primary-btn" })
                            }

                            @if (User.Identity.GetUserId() != Model.AuthorId)
                            {
                                @Ajax.ActionLink("Report", "Create", "CommentReports", new { area = string.Empty, id = Model.Id }, new AjaxOptions
                                                   {
                                                       HttpMethod = "GET",
                                                       InsertionMode = InsertionMode.Replace,
                                                       UpdateTargetId = $"comment-action-container-{@Model.Id}"
                                                   }, new { @class = "btn btn-link link-btn pull-right" })
                            }
                        </div>
                    </div>
                </div>
            </div>

            <div class="meta-info" id="comment-action-container-@Model.Id"></div>
            <div id="comment-action-success-@Model.Id"></div>
        }
    </article>
</div>

<script>
    function DeleteCommentConfirm_@(Model.Id)() {
        $('#delete-comment-confirm-@Model.Id').modal('show');
    }

    function LoadCommentReports_@(Model.Id)() {
        $('#comment-reports-@Model.Id').modal('show');
    }
</script>