Web/ForumSystem.Web/ViewModels/Notifications/NotificationViewModel.cs
namespace ForumSystem.Web.ViewModels.Notifications
{
    using System;

    using AutoMapper;

    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure.Mapping;

    public class NotificationViewModel : IMapFrom<Notification>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public int? ItemId { get; set; }

        public string SenderId { get; set; }

        public string Sender { get; set; }

        public string ReceiverId { get; set; }

        public string Receiver { get; set; }

        public NotificationType NotificationType { get; set; }

        public bool IsChecked { get; set; }

        public DateTime CreatedOn { get; set; }

        public void CreateMappings(IMapperConfiguration configuration)
        {
            configuration.CreateMap<Notification, NotificationViewModel>()
                .ForMember(n => n.Receiver, config => config.MapFrom(n => n.Receiver.UserName));
            configuration.CreateMap<Notification, NotificationViewModel>()
                .ForMember(n => n.Sender, config => config.MapFrom(n => n.Sender.UserName));
        }
    }
}

Web/ForumSystem.Web/Controllers/AnswersController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.Models;
    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.Infrastructure.Extensions;
    using ForumSystem.Web.InputModels.Answers;
    using ForumSystem.Web.ViewModels.Answers;

    using Microsoft.AspNet.Identity;

    public class AnswersController : BaseController
    {
        public AnswersController(IForumSystemData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            var model =
                this.Data.Answers.All()
                    .Where(a => a.Id == id)
                    .ProjectTo<AnswerViewModel>()
                    .FirstOrDefault();

            return this.View(model);
        }

        [ChildActionOnly]
        public ActionResult GetById(int id)
        {
            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            var model = this.Data.Answers.All().Where(a => a.Id == id).ProjectTo<AnswerViewModel>().FirstOrDefault();

            return this.PartialView("_AnswerDetailPartial", model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = this.Data.Posts.GetById(id);
            if (post == null || post.IsDeleted || post.IsLocked)
            {
                return this.HttpNotFound();
            }

            var inputModel = new AnswerInputModel { PostId = post.Id, Post = post.Title };

            return this.PartialView(inputModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AnswerInputModel input)
        {
            if (input != null && this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var answer = new Answer
                                 {
                                     Content = input.Content,
                                     PostId = input.PostId,
                                     AuthorId = userId
                                 };

                this.Data.Answers.Add(answer);
                this.Data.SaveChanges();

                var post = this.Data.Posts.GetById(answer.PostId);
                post.LastActivity = answer.CreatedOn;

                this.Data.Posts.Update(post);
                this.Data.SaveChanges();

                if (post.AuthorId != userId)
                {
                    var newNotification = new Notification
                                              {
                                                  NotificationType = NotificationType.AnswerPost,
                                                  ItemId = answer.Id,
                                                  SenderId = userId,
                                                  ReceiverId = post.AuthorId
                                              };

                    this.Data.Notifications.Add(newNotification);
                    this.Data.SaveChanges();

                    this.UpdateNotificationsCount(post.Author);
                }

                var viewModel = Mapper.Map<AnswerViewModel>(answer);

                return this.PartialView("_AnswerDetailPartial", viewModel);
            }

            return this.JsonError("Content is required");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userId = this.User.Identity.GetUserId();
            var answer = this.Data.Answers.GetById(id);
            if (answer == null)
            {
                return this.HttpNotFound();
            }

            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = new AnswerEditModel { Id = answer.Id, Content = answer.Content };

            return this.PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AnswerEditModel model)
        {
            if (this.ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();
                var answer = this.Data.Answers.GetById(model.Id);

                if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                answer.Content = model.Content;

                this.Data.Answers.Update(answer);
                this.Data.SaveChanges();

                var viewModel = Mapper.Map<AnswerViewModel>(answer);

                return this.PartialView("_AnswerDetailPartial", viewModel);
            }

            return this.JsonError("Content is required");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var answer = this.Data.Answers.GetById(id);
            if (answer == null || answer.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = Mapper.Map<AnswerViewModel>(answer);

            return this.PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var answer = this.Data.Answers.GetById(id);
            if (answer == null || answer.IsDeleted)
            {
                return this.HttpNotFound();
            }

            var userId = this.User.Identity.GetUserId();
            if (answer.AuthorId != userId && !this.User.IsModerator() && !this.User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            this.Data.Answers.Delete(id);
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", "Posts", new { area = string.Empty, id = answer.PostId });
        }
    }
}

Web/ForumSystem.Web/Controllers/NotificationsController.cs
namespace ForumSystem.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.UnitOfWork;
    using ForumSystem.Web.Controllers.Base;
    using ForumSystem.Web.ViewModels.Notifications;

    using Microsoft.AspNet.Identity;

    using PagedList;

    using WebGrease.Css.Extensions;

    [Authorize]
    public class NotificationsController : BaseController
    {
        private const int NotificationsOnFirstLoadDefaultValue = 6;

        private const int NotificationsOnAjaxLoadDefaultValue = 4;

        private const int NotificationsPerPageDefaultValue = 10;

        public NotificationsController(IForumSystemData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult All(int? page)
        {
            var userId = this.User.Identity.GetUserId();
            var pageNumber = page ?? 1;
            var notifications =
                this.Data.Notifications.All()
                    .Where(n => n.ReceiverId == userId)
                    .OrderByDescending(n => n.CreatedOn)
                    .ProjectTo<NotificationViewModel>()
                    .ToList();

            this.Data.Notifications.All()
                .Where(n => n.ReceiverId == userId && !n.IsChecked)
                .ForEach(n => n.IsChecked = true);

            this.Data.SaveChanges();

            var model = notifications.ToPagedList(pageNumber, NotificationsPerPageDefaultValue);

            return this.View(model);
        }

        [HttpGet]
        public ActionResult GetLastNotifications()
        {
            var userId = this.User.Identity.GetUserId();
            var lastNotications =
                this.Data.Notifications.All()
                    .Where(n => n.ReceiverId == userId)
                    .OrderBy(n => n.IsChecked)
                    .ThenByDescending(n => n.CreatedOn)
                    .Take(NotificationsOnFirstLoadDefaultValue)
                    .ProjectTo<NotificationViewModel>()
                    .ToList();

            this.Data.Notifications.All()
                .Where(n => n.ReceiverId == userId)
                .OrderBy(n => n.IsChecked)
                .ThenByDescending(n => n.CreatedOn)
                .Take(NotificationsOnFirstLoadDefaultValue)
                .ForEach(n => n.IsChecked = true);

            this.Data.SaveChanges();

            return this.PartialView("_LastNotificationsPartial", lastNotications);
        }

        public ActionResult LoadMoreNotifications(string dateOfLastNotification)
        {
            if (dateOfLastNotification == null)
            {
                return null;
            }

            var date = DateTime.Parse(dateOfLastNotification);
            var userId = this.User.Identity.GetUserId();
            var user = this.Data.Users.GetById(userId);

            var olderNotifications =
                this.Data.Notifications.All()
                    .Where(n => n.ReceiverId == userId && n.CreatedOn < date)
                    .OrderBy(n => n.IsChecked)
                    .ThenByDescending(n => n.CreatedOn)
                    .Take(NotificationsOnAjaxLoadDefaultValue)
                    .ProjectTo<NotificationViewModel>()
                    .ToList();

            this.Data.Notifications.All()
                .Where(n => n.ReceiverId == userId && n.CreatedOn < date)
                .OrderBy(n => n.IsChecked)
                .ThenByDescending(n => n.CreatedOn)
                .Take(NotificationsOnAjaxLoadDefaultValue)
                .ForEach(n => n.IsChecked = true);

            this.Data.SaveChanges();

            this.UpdateNotificationsCount(user);

            return this.PartialView("_LastNotificationsPartial", olderNotifications);
        }

        [HttpGet]
        public ActionResult GetNotificationsCount()
        {
            var userId = this.User.Identity.GetUserId();
            var user = this.Data.Users.All().FirstOrDefault(u => u.Id == userId);
            var notificationsCount = user.ReceivedNotifications.Count(n => !n.IsChecked);

            return this.Content(notificationsCount.ToString());
        }
    }
}

Web/ForumSystem.Web/Views/Notifications/All.cshtml
@using ForumSystem.Data.Models
@using PagedList.Mvc

@model PagedList.IPagedList<ForumSystem.Web.ViewModels.Notifications.NotificationViewModel>

@{
    ViewBag.Title = "Your Notifications";
    Layout = "~/Views/Shared/_UserPageLayout.cshtml";
}

<div class="notifications-wrapper">
    <ul class="notifications">
        @foreach (var item in Model)
        {
            if (item.NotificationType == NotificationType.AnswerPost)
            {
                if (!item.IsChecked)
                {
                    <li class="noti-wrap table-holder highlighted">
                        @Html.Partial("_AnswerPostNotificationDetailPartial", item)
                    </li>
                }
                else
                {
                    <li class="noti-wrap table-holder">
                        @Html.Partial("_AnswerPostNotificationDetailPartial", item)
                    </li>
                }
            }

            if (item.NotificationType == NotificationType.CommentAnswer)
            {
                if (!item.IsChecked)
                {
                    <li class="noti-wrap table-holder highlighted">
                        @Html.Partial("_CommentAnswerNotificationDetailPartial", item)
                    </li>
                }
                else
                {
                    <li class="noti-wrap table-holder">
                        @Html.Partial("_CommentAnswerNotificationDetailPartial", item)
                    </li>
                }
            }

            if (item.NotificationType == NotificationType.LikePost)
            {
                if (!item.IsChecked)
                {
                    <li class="noti-wrap table-holder highlighted">
                        @Html.Partial("_LikePostNotificationDetailPartial", item)
                    </li>
                }
                else
                {
                    <li class="noti-wrap table-holder">
                        @Html.Partial("_LikePostNotificationDetailPartial", item)
                    </li>
                }
            }

            if (item.NotificationType == NotificationType.LikeAnswer)
            {
                if (!item.IsChecked)
                {
                    <li class="noti-wrap table-holder highlighted">
                        @Html.Partial("_LikeAnswerNotificationDetailPartial", item)
                    </li>
                }
                else
                {
                    <li class="noti-wrap table-holder">
                        @Html.Partial("_LikeAnswerNotificationDetailPartial", item)
                    </li>
                }
            }

            if (item.NotificationType == NotificationType.LikeComment)
            {
                if (!item.IsChecked)
                {
                    <li class="noti-wrap table-holder highlighted">
                        @Html.Partial("_LikeCommentNotificationDetailPartial", item)
                    </li>
                }
                else
                {
                    <li class="noti-wrap table-holder">
                        @Html.Partial("_LikeCommentNotificationDetailPartial", item)
                    </li>
                }
            }
        }
    </ul>

    @if (Model.HasNextPage || Model.HasPreviousPage)
    {
        <div class="pagination-container">
            <div class="inner-holder">
                @Html.PagedListPager(Model, page => Url.Action("All", new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        $('#notifications-item').addClass('head-nav-selected-item');
    });
</script>

Web/ForumSystem.Web/Views/Notifications/_AnswerPostNotificationDetailPartial.cshtml
@model ForumSystem.Web.ViewModels.Notifications.NotificationViewModel

<div class="noti-details table-holder">
    <span class="cell msg-photo">
        <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
            @Html.Action("GetUserImage", "Users", new { area = string.Empty, id = Model.SenderId })
        </a>
    </span>
    <span class="cell msg-body">
        <span class="msg-title">
            <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
                <span>@Model.Sender</span>
            </a>
            <a href="@Url.Action("Details", "Answers", new { area = string.Empty, id = Model.ItemId })" class="msg-text">
                <span> answered on your post.</span>
            </a>
        </span>
        <span class="msg-time" created-on="@Model.CreatedOn">
            <i class="fa fa-comment"></i>
            <span>@Model.CreatedOn</span>
        </span>
    </span>
</div>

Web/ForumSystem.Web/Views/Notifications/_CommentAnswerNotificationDetailPartial.cshtml
@model ForumSystem.Web.ViewModels.Notifications.NotificationViewModel

<div class="noti-details table-holder">
    <span class="cell msg-photo">
        <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
            @Html.Action("GetUserImage", "Users", new { area = string.Empty, id = Model.SenderId })
        </a>
    </span>
    <span class="cell msg-body">
        <span class="msg-title">
            <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
                <span>@Model.Sender</span>
            </a>
            <a href="@Url.Action("Details", "Comments", new { area = string.Empty, id = Model.ItemId })" class="msg-text">
                <span> commented on your answer.</span>
            </a>
        </span>
        <span class="msg-time" created-on="@Model.CreatedOn">
            <i class="fa fa-comment"></i>
            <span>@Model.CreatedOn</span>
        </span>
    </span>
</div>

Web/ForumSystem.Web/Views/Notifications/_LastNotificationsPartial.cshtml
@using System.Collections.Generic
@using ForumSystem.Data.Models

@model IEnumerable<ForumSystem.Web.ViewModels.Notifications.NotificationViewModel>

@foreach (var item in Model)
{
    if (item.NotificationType == NotificationType.AnswerPost)
    {
        if (!item.IsChecked)
        {
            <li class="noti-wrap table-holder highlighted">
                @Html.Partial("_AnswerPostNotificationDetailPartial", item)
            </li>
        }
        else
        {
            <li class="noti-wrap table-holder">
                @Html.Partial("_AnswerPostNotificationDetailPartial", item)
            </li>
        }
    }

    if (item.NotificationType == NotificationType.CommentAnswer)
    {
        if (!item.IsChecked)
        {
            <li class="noti-wrap table-holder highlighted">
                @Html.Partial("_CommentAnswerNotificationDetailPartial", item)
            </li>
        }
        else
        {
            <li class="noti-wrap table-holder">
                @Html.Partial("_CommentAnswerNotificationDetailPartial", item)
            </li>
        }
    }

    if (item.NotificationType == NotificationType.LikePost)
    {
        if (!item.IsChecked)
        {
            <li class="noti-wrap table-holder highlighted">
                @Html.Partial("_LikePostNotificationDetailPartial", item)
            </li>
        }
        else
        {
            <li class="noti-wrap table-holder">
                @Html.Partial("_LikePostNotificationDetailPartial", item)
            </li>
        }
    }

    if (item.NotificationType == NotificationType.LikeAnswer)
    {
        if (!item.IsChecked)
        {
            <li class="noti-wrap table-holder highlighted">
                @Html.Partial("_LikeAnswerNotificationDetailPartial", item)
            </li>
        }
        else
        {
            <li class="noti-wrap table-holder">
                @Html.Partial("_LikeAnswerNotificationDetailPartial", item)
            </li>
        }
    }

    if (item.NotificationType == NotificationType.LikeComment)
    {
        if (!item.IsChecked)
        {
            <li class="noti-wrap table-holder highlighted">
                @Html.Partial("_LikeCommentNotificationDetailPartial", item)
            </li>
        }
        else
        {
            <li class="noti-wrap table-holder">
                @Html.Partial("_LikeCommentNotificationDetailPartial", item)
            </li>
        }
    }
}

<script>
    var ajaxLoading = false;
    function loadNotifications() {
        $.ajax({
            url: '@Url.Action("LoadMoreNotifications", "Notifications")',
            data: { dateOfLastNotification: $('#notifications-container li').last().find('.msg-time').attr('created-on') },
            success: function (data) {
                $('#notifications-container').append(data), function() {
                    ajaxLoading = false;
                };
            }
        });
    }

    $(document).ready(function () {
        var element = $('#notifications-container');
        element.scroll(function () {
            if (Math.ceil(element[0].scrollHeight - element.scrollTop()) == element.outerHeight()) {
                if (!ajaxLoading) {
                    ajaxLoading = true;
                    loadNotifications();
                }
            }
        });

        $(document).ajaxStart(function () {
            $('#loading-on-scroll').css("display", "block");
        });

        $(document).ajaxComplete(function () {
            $('#loading-on-scroll').css("display", "none");
        });
    });
</script>

Web/ForumSystem.Web/Views/Notifications/_LikeAnswerNotificationDetailPartial.cshtml
@model ForumSystem.Web.ViewModels.Notifications.NotificationViewModel

<div class="noti-details table-holder">
    <span class="cell msg-photo">
        <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
            @Html.Action("GetUserImage", "Users", new { area = string.Empty, id = Model.SenderId })
        </a>
    </span>
    <span class="cell msg-body">
        <span class="msg-title">
            <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
                <span>@Model.Sender</span>
            </a>
            <a href="@Url.Action("Details", "Answers", new { area = string.Empty, id = Model.ItemId })" class="msg-text">
                <span> likes your answer.</span>
            </a>
        </span>
        <span class="msg-time" created-on="@Model.CreatedOn">
            <i class="fa fa-thumbs-up"></i>
            <span>@Model.CreatedOn</span>
        </span>
    </span>
</div>

Web/ForumSystem.Web/Views/Notifications/_LikeCommentNotificationDetailPartial.cshtml
@model ForumSystem.Web.ViewModels.Notifications.NotificationViewModel

<div class="noti-details table-holder">
    <span class="cell msg-photo">
        <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
            @Html.Action("GetUserImage", "Users", new { area = string.Empty, id = Model.SenderId })
        </a>
    </span>
    <span class="cell msg-body">
        <span class="msg-title">
            <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
                <span>@Model.Sender</span>
            </a>
            <a href="@Url.Action("Details", "Comments", new { area = string.Empty, id = Model.ItemId })" class="msg-text">
                <span> likes your comment.</span>
            </a>
        </span>
        <span class="msg-time" created-on="@Model.CreatedOn">
            <i class="fa fa-thumbs-up"></i>
            <span>@Model.CreatedOn</span>
        </span>
    </span>
</div>

Web/ForumSystem.Web/Views/Notifications/_LikePostNotificationDetailPartial.cshtml
@model ForumSystem.Web.ViewModels.Notifications.NotificationViewModel

<div class="noti-details table-holder">
    <span class="cell msg-photo">
        <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
            @Html.Action("GetUserImage", "Users", new { area = string.Empty, id = Model.SenderId })
        </a>
    </span>
    <span class="cell msg-body">
        <span class="msg-title">
            <a href="@Url.Action("Details", "Users", new { area = string.Empty, id = Model.SenderId })">
                <span>@Model.Sender</span>
            </a>
            <a href="@Url.Action("Details", "Posts", new { area = string.Empty, id = Model.ItemId })" class="msg-text">
                <span> likes your post.</span>
            </a>
        </span>
        <span class="msg-time" created-on="@Model.CreatedOn">
            <i class="fa fa-thumbs-up"></i>
            <span>@Model.CreatedOn</span>
        </span>
    </span>
</div>